 -- StayFlow complete Supabase schema
-- Fresh install + safe rerun for the uploaded v5 cancellation-email application.
-- Run in Supabase SQL Editor for the SAME project used by DATABASE_URL.


begin;

create table if not exists public.users (
    id bigint generated by default as identity primary key,
    auth_user_id uuid unique references auth.users(id) on delete cascade,
    username text unique not null,
    role text not null default 'guest'
        check (role in ('admin', 'manager', 'guest')),
    email text unique not null,
    created_at timestamptz not null default now()
);

create table if not exists public.hotels (
    id bigint generated by default as identity primary key,
    name text not null,
    location text not null,
    description text,
    image text,
    manager_id bigint references public.users(id) on delete set null,
    rating numeric(2,1) default 4.5
        check (rating between 0 and 5),
    created_at timestamptz not null default now()
);

create table if not exists public.rooms (
    id bigint generated by default as identity primary key,
    hotel_id bigint not null references public.hotels(id) on delete cascade,
    room_number text not null,
    room_type text not null,
    price numeric(12,2) not null check (price >= 0),
    available boolean not null default true,
    image text,
    amenities text,
    unique (hotel_id, room_number)
);


create table if not exists public.bookings (
    id bigint generated by default as identity primary key,
    guest_id bigint not null references public.users(id) on delete cascade,
    room_id bigint not null references public.rooms(id) on delete cascade,
    hotel_id bigint not null references public.hotels(id) on delete cascade,
    check_in date not null,
    check_out date not null,
    status text not null default 'Booked',
    created_at timestamptz not null default now(),
    constraint bookings_dates_check check (check_out > check_in)
);

create table if not exists public.cancellation_requests (
    id bigint generated by default as identity primary key,
    booking_id bigint not null references public.bookings(id) on delete cascade,
    guest_id bigint not null references public.users(id) on delete cascade,
    hotel_id bigint not null references public.hotels(id) on delete cascade,
    assigned_manager_id bigint references public.users(id) on delete set null,
    reason text,
    status text not null default 'Pending'
        check (status in ('Pending', 'Approved', 'Rejected')),
    manager_note text,
    created_at timestamptz not null default now(),
    reviewed_at timestamptz
);

create table if not exists public.notifications (
    id bigint generated by default as identity primary key,
    user_id bigint not null references public.users(id) on delete cascade,
    title text not null,
    message text not null,
    is_read boolean not null default false,
    created_at timestamptz not null default now()
);

-- Forward-compatible columns for databases created by older StayFlow versions.
alter table public.cancellation_requests
    add column if not exists assigned_manager_id bigint
    references public.users(id) on delete set null;

-- Normalize the booking status constraint to exactly what app.py writes.
do $$
declare
    c record;
begin
    for c in
        select conname
        from pg_constraint
        where conrelid = 'public.bookings'::regclass
          and contype = 'c'
          and pg_get_constraintdef(oid) ilike '%status%'
    loop
        execute format('alter table public.bookings drop constraint %I', c.conname);
    end loop;

    if not exists (
        select 1
        from pg_constraint
        where conrelid = 'public.bookings'::regclass
          and conname = 'bookings_status_check'
    ) then
        alter table public.bookings
            add constraint bookings_status_check
            check (status in ('Booked', 'Checked-in', 'Checked-out', 'Cancelled'));
    end if;
end $$;

create index if not exists idx_rooms_hotel
    on public.rooms(hotel_id);

create index if not exists idx_bookings_guest
    on public.bookings(guest_id);

create index if not exists idx_bookings_hotel
    on public.bookings(hotel_id);

create index if not exists idx_bookings_room
    on public.bookings(room_id);

create index if not exists idx_hotels_manager
    on public.hotels(manager_id);

create index if not exists idx_cancellation_booking
    on public.cancellation_requests(booking_id);

create index if not exists idx_cancellation_guest
    on public.cancellation_requests(guest_id);

create index if not exists idx_cancellation_hotel
    on public.cancellation_requests(hotel_id);

create index if not exists idx_cancellation_assigned_manager
    on public.cancellation_requests(assigned_manager_id, status, created_at desc);

create index if not exists idx_notifications_user
    on public.notifications(user_id, created_at desc);

-- Backfill cancellation ownership for rows created before assigned_manager_id existed.
update public.cancellation_requests cr
set assigned_manager_id = h.manager_id
from public.hotels h
where cr.hotel_id = h.id
  and cr.assigned_manager_id is null
  and h.manager_id is not null;

-- The Flask backend is the trusted database boundary.
-- No anon/authenticated Supabase API policies are created intentionally.
alter table public.users enable row level security;
alter table public.hotels enable row level security;
alter table public.rooms enable row level security;
alter table public.bookings enable row level security;
alter table public.cancellation_requests enable row level security;
alter table public.notifications enable row level security;

commit;
